# Generated by Django 4.2.4 on 2023-09-01 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0004_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-id', 'author')},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ('-timestamp', '-id')},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 1, 2, 12, 5, 712120, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
