# Generated by Django 4.2.4 on 2023-09-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0019_alter_blogpost_image_alter_comment_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('id', 'rank')},
        ),
    ]
