# Generated by Django 4.2.4 on 2023-09-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0020_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
