# Generated by Django 4.2.4 on 2023-09-25 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0022_blogpost_recent_activity_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='recent_activity_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
