# Generated by Django 4.2.4 on 2023-09-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0023_alter_blogpost_recent_activity_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='recent_activity_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
