# Generated by Django 4.2.4 on 2023-10-15 02:10

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('townapp', '0026_alter_comment_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('text_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('link_color', colorfield.fields.ColorField(default='#0000FF', image_field=None, max_length=25, samples=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'id'),
            },
        ),
    ]
