# Generated by Django 4.2.4 on 2023-10-23 21:37

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0028_userpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='embed',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
