# Generated by Django 4.2.4 on 2023-10-23 22:01

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0029_blogpost_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='embed',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
