# Generated by Django 4.2.4 on 2023-11-01 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0030_comment_embed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=999)),
                ('description', models.TextField(blank=True)),
                ('date', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-rank', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=0)),
                ('track_name', models.CharField(blank=True, max_length=999)),
                ('track_author', models.CharField(blank=True, max_length=999)),
                ('track_description', models.TextField(blank=True)),
                ('audio', models.FileField(blank=True, upload_to='')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='townapp.challenge')),
            ],
            options={
                'ordering': ('-rank', 'track_name'),
            },
        ),
    ]
