# Generated by Django 4.2.4 on 2023-11-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0031_challenge_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='date',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
