# Generated by Django 4.2.4 on 2023-11-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0032_challenge_slug_alter_challenge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
