# Generated by Django 4.2.4 on 2024-10-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0033_challenge_ongoing'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='custom_font',
            field=models.FileField(blank=True, null=True, upload_to='fonts/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='font_family',
            field=models.CharField(choices=[('Times New Roman', 'Times New Roman'), ('Helvetica', 'Helvetica'), ('Courier', 'Courier')], default='Times New Roman', max_length=100),
        ),
    ]
