# Generated by Django 4.2.4 on 2024-10-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('townapp', '0036_alter_theme_custom_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='font_family',
            field=models.CharField(choices=[('Times', 'Times'), ('Helvetica', 'Helvetica'), ('Courier', 'Courier')], default='Times', max_length=100),
        ),
    ]
